---
name: Catalyst-Plugin-Session-State-Stash
version: 0.12
author:
  - "James Laver <perl -e 'printf(qw/%s@%s.com cpan jameslaver/);'>"
abstract: Maintain session IDs using the stash
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::MockObject: 0
  Test::More: 0
  Test::WWW::Mechanize::Catalyst: 0
  URI::Escape: 0
requires:
  Catalyst::Plugin::Session: 0.27
  Class::Accessor::Fast: 0
  MRO::Compat: 0
configure_requires:
  Module::Build: 0.34
provides:
  Catalyst::Plugin::Session::State::Stash:
    file: lib/Catalyst/Plugin/Session/State/Stash.pm
    version: 0.12
generated_by: Module::Build version 0.34
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
